;;; mojo-layer-tests.el --- Tests for Mojo layer -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Richard Johnsson

;;; Commentary:

;; ERT tests for command generation and command dispatch helpers in funcs.el.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'subr-x)

;; Minimal stubs so funcs.el can load outside a full Spacemacs session.
(unless (fboundp 'configuration-layer/layer-used-p)
  (defun configuration-layer/layer-used-p (&rest _args)
    "Stub used in test context."
    nil))

(unless (fboundp 'spacemacs/declare-prefix-for-mode)
  (defun spacemacs/declare-prefix-for-mode (&rest _args)
    "Stub used in test context."
    nil))

(unless (fboundp 'spacemacs/set-leader-keys-for-major-mode)
  (defun spacemacs/set-leader-keys-for-major-mode (&rest _args)
    "Stub used in test context."
    nil))

(unless (fboundp 'spacemacs|define-jump-handlers)
  (defmacro spacemacs|define-jump-handlers (&rest _args)
    "Stub used in test context."
    nil))

;; Layer variables expected by funcs.el.
(defvar mojo-format-on-save nil)
(defvar mojo-indent-offset 4)
(defvar mojo-repl-arguments '("repl"))
(defvar mojo-build-arguments nil)
(defvar mojo-use-project-pixi nil)
(defvar mojo-use-global-pixi nil)
(defvar mojo-global-pixi-env-priority '("mojo" "default"))
(defvar mojo-pixi-no-progress nil)
(defvar mojo-run-arguments nil)
(defvar mojo-run-project-entrypoint nil)
(defvar mojo-run-entrypoint-candidates '("main.mojo"))
(defvar mojo-test-arguments nil)
(defvar mojo-test-project-target nil)
(defvar mojo-test-target-candidates '("tests"))
(defvar mojo-test-add-project-include t)
(defvar mojo-clean-command nil)
(defvar mojo-stdlib-path nil)
(defvar mojo-extra-source-paths nil)

(let* ((this-file (or load-file-name buffer-file-name))
       (repo-root (expand-file-name ".." (file-name-directory this-file))))
  (load-file (expand-file-name "funcs.el" repo-root)))

(ert-deftest mojo-test-mojo-command-quotes-target ()
  (cl-letf (((symbol-function 'mojo//resolve-mojo-command)
             (lambda () "mojo")))
    (let ((command (mojo//mojo-command "run"
                                       '("--target" "cpu")
                                       "/tmp/mojo project/main.mojo")))
      (should (string-match-p "^mojo run --target cpu " command))
      (should (string-match-p "/tmp/mojo\\\\ project/main\\.mojo$" command)))))

(ert-deftest mojo-test-resolve-mojo-command-prefers-pixi-run ()
  (let* ((root (make-temp-file "mojo-layer-" t))
         (mojo-use-project-pixi t)
         (project-mojo (expand-file-name ".pixi/envs/default/bin/mojo" root)))
    (make-directory (file-name-directory project-mojo) t)
    (with-temp-file project-mojo
      (insert "#!/bin/sh\n"))
    (set-file-modes project-mojo #o755)
    (cl-letf (((symbol-function 'mojo//project-root) (lambda () root))
              ((symbol-function 'executable-find)
               (lambda (name)
                 (when (string= name "pixi")
                   "/usr/bin/pixi"))))
      (should (string=
               (mojo//resolve-mojo-command)
               "pixi run mojo")))))

(ert-deftest mojo-test-resolve-mojo-command-falls-back-to-project-pixi-binary ()
  (let* ((root (make-temp-file "mojo-layer-" t))
         (mojo-use-project-pixi t)
         (project-mojo (expand-file-name ".pixi/envs/default/bin/mojo" root)))
    (make-directory (file-name-directory project-mojo) t)
    (with-temp-file project-mojo
      (insert "#!/bin/sh\n"))
    (set-file-modes project-mojo #o755)
    (cl-letf (((symbol-function 'mojo//project-root) (lambda () root))
              ((symbol-function 'executable-find)
               (lambda (_name) nil)))
      (should (string=
               (mojo//resolve-mojo-command)
               (shell-quote-argument project-mojo))))))

(ert-deftest mojo-test-resolve-mojo-command-uses-pixi-run ()
  (let ((mojo-use-project-pixi t))
    (cl-letf (((symbol-function 'mojo//project-has-pixi-p) (lambda () t))
              ((symbol-function 'mojo//project-pixi-mojo-path) (lambda () nil))
              ((symbol-function 'executable-find)
               (lambda (name)
                 (when (string= name "pixi")
                   "/usr/bin/pixi"))))
      (should (string= (mojo//resolve-mojo-command) "pixi run mojo")))))

(ert-deftest mojo-test-resolve-mojo-command-uses-pixi-run-no-progress ()
  (let ((mojo-use-project-pixi t)
        (mojo-pixi-no-progress t))
    (cl-letf (((symbol-function 'mojo//project-has-pixi-p) (lambda () t))
              ((symbol-function 'mojo//project-pixi-mojo-path) (lambda () nil))
              ((symbol-function 'executable-find)
               (lambda (name)
                 (when (string= name "pixi")
                   "/usr/bin/pixi"))))
      (should (string= (mojo//resolve-mojo-command)
                       "pixi run --no-progress mojo")))))

(ert-deftest mojo-test-resolve-mojo-command-uses-global-pixi-fallback ()
  (let ((mojo-use-project-pixi nil)
        (mojo-use-global-pixi t))
    (cl-letf (((symbol-function 'mojo//global-pixi-tool-path)
               (lambda (_tool) "/tmp/global pixi/mojo"))
              ((symbol-function 'executable-find)
               (lambda (_name) nil)))
      (should (string= (mojo//resolve-mojo-command)
                       "/tmp/global\\ pixi/mojo")))))

(ert-deftest mojo-test-project-entrypoint-explicit ()
  (let ((root (make-temp-file "mojo-layer-" t))
        (mojo-run-project-entrypoint "src/my_main.mojo")
        (mojo-run-entrypoint-candidates '("main.mojo")))
    (cl-letf (((symbol-function 'mojo//project-root) (lambda () root)))
      (should (string=
               (mojo//project-entrypoint)
               (expand-file-name "src/my_main.mojo" root))))))

(ert-deftest mojo-test-project-entrypoint-autodetect ()
  (let* ((root (make-temp-file "mojo-layer-" t))
         (entrypoint (expand-file-name "src/main.mojo" root))
         (mojo-run-project-entrypoint nil)
         (mojo-run-entrypoint-candidates '("main.mojo" "src/main.mojo")))
    (make-directory (file-name-directory entrypoint) t)
    (with-temp-file entrypoint
      (insert "def main() raises:\n    pass\n"))
    (cl-letf (((symbol-function 'mojo//project-root) (lambda () root)))
      (should (string= (mojo//project-entrypoint) entrypoint)))))

(ert-deftest mojo-test-run-project-uses-entrypoint ()
  (let* ((root (make-temp-file "mojo-layer-" t))
         (entrypoint (expand-file-name "main.mojo" root))
         (captured nil)
         (mojo-run-arguments '("--target" "cpu"))
         (mojo-run-project-entrypoint "main.mojo")
         (mojo-use-project-pixi nil))
    (with-temp-file entrypoint
      (insert "def main() raises:\n    pass\n"))
    (cl-letf (((symbol-function 'compile)
               (lambda (command)
                 (setq captured command)
                 command))
              ((symbol-function 'executable-find)
               (lambda (name)
                 (when (string= name "mojo")
                   "mojo")))
              ((symbol-function 'mojo//project-root)
               (lambda () root)))
      (mojo/run-project)
      (should (equal captured
                     (format "mojo run --target cpu %s" entrypoint))))))

(ert-deftest mojo-test-build-project-uses-entrypoint ()
  (let* ((root (make-temp-file "mojo-layer-" t))
         (entrypoint (expand-file-name "src/main.mojo" root))
         (captured nil)
         (mojo-build-arguments '("--emit" "llvm"))
         (mojo-run-project-entrypoint "src/main.mojo")
         (mojo-use-project-pixi nil))
    (make-directory (file-name-directory entrypoint) t)
    (with-temp-file entrypoint
      (insert "def main() raises:\n    pass\n"))
    (cl-letf (((symbol-function 'compile)
               (lambda (command)
                 (setq captured command)
                 command))
              ((symbol-function 'executable-find)
               (lambda (name)
                 (when (string= name "mojo")
                   "mojo")))
              ((symbol-function 'mojo//project-root)
               (lambda () root)))
      (mojo/build-project)
      (should (equal captured
                     (format "mojo build --emit llvm %s" entrypoint))))))

(ert-deftest mojo-test-test-project-uses-mojo-run ()
  (let* ((root (make-temp-file "mojo-layer-" t))
         (tests-dir (expand-file-name "tests" root))
         (captured nil)
         (mojo-test-project-target nil)
         (mojo-test-target-candidates '("tests"))
         (mojo-test-add-project-include t)
         (mojo-test-arguments '("--warn-on-unstable-apis"))
         (mojo-use-project-pixi nil))
    (make-directory tests-dir t)
    (cl-letf (((symbol-function 'compile)
               (lambda (command)
                 (setq captured command)
                 command))
              ((symbol-function 'executable-find)
               (lambda (name)
                 (when (string= name "mojo")
                   "mojo")))
              ((symbol-function 'mojo//project-root)
               (lambda () root)))
      (mojo/test-project)
      (should (equal captured
                     (format "mojo run -I %s --warn-on-unstable-apis %s"
                             root
                             tests-dir))))))

(ert-deftest mojo-test-clean-project-uses-pixi-clean-default ()
  (let ((captured nil)
        (mojo-clean-command nil)
        (mojo-use-project-pixi t)
        (mojo-pixi-no-progress nil))
    (cl-letf (((symbol-function 'compile)
               (lambda (command)
                 (setq captured command)
                 command))
              ((symbol-function 'mojo//project-root)
               (lambda () "/tmp/mojo-layer-root"))
              ((symbol-function 'mojo//project-has-pixi-p)
               (lambda () t))
              ((symbol-function 'executable-find)
               (lambda (name)
                 (when (string= name "pixi")
                   "/usr/bin/pixi"))))
      (mojo/clean-project)
      (should (equal captured "pixi clean")))))

(ert-deftest mojo-test-test-dwim-prefers-test-file ()
  (let ((project-called nil)
        (file-called nil))
    (cl-letf (((symbol-function 'buffer-file-name)
               (lambda (&optional _buffer) "/tmp/project/tests/test_math.mojo"))
              ((symbol-function 'mojo/test-project)
               (lambda () (setq project-called t)))
              ((symbol-function 'mojo/test-file)
               (lambda (file) (setq file-called file))))
      (mojo/test-dwim)
      (should (string= file-called "/tmp/project/tests/test_math.mojo"))
      (should-not project-called))))

(ert-deftest mojo-test-test-dwim-falls-back-to-project ()
  (let ((project-called nil)
        (file-called nil))
    (cl-letf (((symbol-function 'buffer-file-name)
               (lambda (&optional _buffer) "/tmp/project/src/math.mojo"))
              ((symbol-function 'mojo/test-project)
               (lambda () (setq project-called t)))
              ((symbol-function 'mojo/test-file)
               (lambda (file) (setq file-called file))))
      (mojo/test-dwim)
      (should project-called)
      (should-not file-called))))

(ert-deftest mojo-test-retest-errors-without-history ()
  (let ((mojo--last-test-command nil))
    (should-error (mojo/retest) :type 'user-error)))

(provide 'mojo-layer-tests)

;;; mojo-layer-tests.el ends here
